id = "blanche"
name = "Blanche"
version = "0.0.2"
schema_version = 1
authors = ["OJ Kwon <oj@inbox.kwon.page>"]
description = "Non official port of VS Code Blanche theme"
repository = "https://github.com/kwonoj/zed-blanche"
